<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>title_stats</name>
   <tag></tag>
   <elementGuidId>179bd9a9-fc97-44de-be78-399c640cacea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='main']/div[4]/div/div/div/h2</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.content > h2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;Stats&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>3ef507d8-8f63-4e61-8a15-dbfb08dd900d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Stats</value>
      <webElementGuid>bd353491-4876-467d-9e27-f3c265fa047d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;account_page_data&quot;]/div[@class=&quot;inner_block&quot;]/div[@class=&quot;inner_content&quot;]/div[@class=&quot;content&quot;]/h2[1]</value>
      <webElementGuid>34da4a76-4963-4739-b4fb-0bdbd00e682c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='main']/div[4]/div/div/div/h2</value>
      <webElementGuid>43d31b0e-856e-4d7d-af01-1a5a4fd7bb32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TV Shows'])[6]/following::h2[1]</value>
      <webElementGuid>d0843f6f-5970-4d23-bfaf-3e3911fb3976</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Movies'])[6]/following::h2[1]</value>
      <webElementGuid>5f0b4097-3ffe-49b3-9d4c-6a9b30e51d4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total Edits'])[1]/preceding::h2[1]</value>
      <webElementGuid>7043269d-b9c8-41b1-8b79-02777fb5ffbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total Ratings'])[1]/preceding::h2[2]</value>
      <webElementGuid>78b75d85-beb5-4ca1-984b-f8f63237b036</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Stats']/parent::*</value>
      <webElementGuid>f047d9c4-037d-4c41-9252-a24865eaf467</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/h2</value>
      <webElementGuid>e171d96d-41f8-4742-89e4-3ec2aa46f79b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'Stats' or . = 'Stats')]</value>
      <webElementGuid>5d003803-3419-45ba-a300-bdbeed701a35</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
